name: HACS Check

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.**'
      - '_WIP/**'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ha-monitoring/custom_components/ha_monitoring/brand/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.**'
      - '_WIP/**'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ha-monitoring/custom_components/ha_monitoring/brand/**'

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: "integration"

